"""
processors/sigma_skeleton.py
------------------------------
Generates draft Sigma rule skeletons for ATT&CK techniques with no
detection coverage — the "gap -> rule" step after
processors/correlator.py's detection coverage analysis.

These are STARTING POINTS, not finished rules. A real Sigma rule needs a
genuine logsource and selection logic built from the analyst's own
environment and log sources, which THEORY has no way to know or
fabricate responsibly. What this generates is the boilerplate every
Sigma rule needs regardless — title, a fresh rule id, status,
references, the ATT&CK tag, falsepositives/level scaffolding — pre-
filled from the actor profile THEORY already has, so an analyst starts
from "here's the shape, fill in the logic for your environment" instead
of a blank file. Every TODO placeholder is deliberate and should stay a
TODO until a human fills it in from their own telemetry.
"""
from __future__ import annotations

import uuid
from datetime import date
from typing import Any

LEVEL_FOR_CONFIDENCE = {"HIGH": "high", "MEDIUM": "medium", "LOW": "low"}


def generate_skeleton(
    technique: dict[str, Any],
    actor_name: str,
    *,
    rule_id: str | None = None,
    today: str | None = None,
) -> str:
    """Build one Sigma rule skeleton (as YAML text) for a single gap
    technique. `rule_id`/`today` are overridable only so tests get
    deterministic output — real callers leave them to be generated."""
    tid        = (technique.get("technique_id") or "UNKNOWN").strip().upper()
    name       = technique.get("technique_name") or technique.get("name") or tid
    tactic     = (technique.get("tactic") or "").strip()
    confidence = (technique.get("confidence") or "LOW").upper()
    level      = LEVEL_FOR_CONFIDENCE.get(confidence, "medium")

    rule_id = rule_id or str(uuid.uuid4())
    today   = today or date.today().isoformat()

    tags = []
    if tactic:
        tags.append(f"attack.{tactic.lower().replace(' ', '_')}")
    tags.append(f"attack.{tid.lower()}")

    lines = [
        f"title: {name} — {actor_name} (DRAFT, needs review)",
        f"id: {rule_id}",
        "status: experimental",
        "description: >",
        f"  Draft detection skeleton for {tid} ({name}), generated by THEORY",
        f"  because {actor_name} is reported as using this technique with no",
        "  existing Sigma coverage in this profile. Fill in a real logsource",
        "  and selection logic for your own environment before relying on",
        "  this rule — nothing below the TODO markers is real detection logic.",
        "references:",
        f"  - https://attack.mitre.org/techniques/{tid}/",
        "author: THEORY (auto-generated skeleton — needs analyst review)",
        f"date: {today}",
        "logsource:",
        "  category: TODO  # e.g. process_creation, network_connection, file_event",
        "  product: TODO   # e.g. windows, linux, macos",
        "detection:",
        "  selection:",
        "    TODO: fill in the field/value pairs that identify this behavior",
        "  condition: selection",
        "falsepositives:",
        "  - Unknown — needs review",
        f"level: {level}",
        "tags:",
    ]
    lines.extend(f"  - {t}" for t in tags)
    return "\n".join(lines) + "\n"


def generate_skeletons_for_gaps(profile: dict[str, Any]) -> list[dict[str, Any]]:
    """Generate one skeleton per technique with no detection coverage
    in the profile's correlation gaps (processors/correlator.py's
    coverage.gaps). Returns [] if there's nothing to generate — either
    no gaps, or correlation never ran (no techniques in the profile)."""
    coverage = (profile.get("correlations") or {}).get("coverage") or {}
    gaps     = coverage.get("gaps") or []
    actor_name = profile.get("actor_name") or "Unknown Actor"

    results = []
    for gap in gaps:
        if not gap.get("technique_id"):
            continue
        results.append({
            "technique_id": gap["technique_id"].strip().upper(),
            "confidence":   (gap.get("confidence") or "LOW").upper(),
            "skeleton":     generate_skeleton(gap, actor_name),
        })
    return results
