"""
reporters/navigator_reporter.py
--------------------------------
Exports a THEORY actor profile as an ATT&CK Navigator layer file (v4.5).

The layer can be imported directly into:
  - MITRE ATT&CK Navigator (https://mitre-attack.github.io/attack-navigator/)
  - Local Navigator instances
  - Any tool that accepts ATT&CK Navigator JSON layers

Color coding by confidence:
  HIGH   → #ff6666  (red)    — 2+ independent sources
  MEDIUM → #ffaa00  (amber)  — 1 authoritative source
  LOW    → #ffe680  (yellow) — 1 community source

Sigma coverage:
  Techniques with Sigma rules get a ▸ prefix in their comment and
  a score boost so they visually stand out.

Usage:
  theory --actor APT28 --sources mitre,malpedia,otx --output navigator
  # writes: output/dossiers/apt28.navigator.json

Import into Navigator:
  1. Go to https://mitre-attack.github.io/attack-navigator/
  2. Open Layer → Upload from Local
  3. Select the .navigator.json file
"""

from __future__ import annotations

import json
import logging
import re
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

OUTPUT_DIR   = Path("output/dossiers")
LAYER_FORMAT = "4.5"
NAVIGATOR_VERSION = "5.1.0"
ATTACK_VERSION    = "16"    # current ATT&CK version as of 2026

# Confidence → hex color
CONFIDENCE_COLORS: dict[str, str] = {
    "HIGH":   "#ff6666",   # red   — highest confidence, prioritize defending
    "MEDIUM": "#ffaa00",   # amber — moderate confidence
    "LOW":    "#ffe680",   # yellow — low confidence, investigate further
}

# Confidence → score (used for Navigator sorting/gradient)
CONFIDENCE_SCORES: dict[str, int] = {
    "HIGH":   100,
    "MEDIUM": 60,
    "LOW":    30,
}

# Tactic name → ATT&CK tactic ID (used in technique entries)
TACTIC_SLUGS: dict[str, str] = {
    "Reconnaissance":        "reconnaissance",
    "Resource Development":  "resource-development",
    "Initial Access":        "initial-access",
    "Execution":             "execution",
    "Persistence":           "persistence",
    "Privilege Escalation":  "privilege-escalation",
    "Defense Evasion":       "defense-evasion",
    "Credential Access":     "credential-access",
    "Discovery":             "discovery",
    "Lateral Movement":      "lateral-movement",
    "Collection":            "collection",
    "Command and Control":   "command-and-control",
    "Exfiltration":          "exfiltration",
    "Impact":                "impact",
}


class NavigatorReporter:
    """
    Builds and saves an ATT&CK Navigator v4.5 layer from a THEORY profile.
    """

    def build_layer(self, profile: dict[str, Any]) -> dict[str, Any]:
        """
        Build a Navigator layer dict from a THEORY actor profile.

        Returns a dict ready to be JSON-serialised and imported into Navigator.
        """
        actor_name   = profile.get("actor_name", "Unknown Actor")
        origin       = profile.get("origin", "")
        motivations  = ", ".join(profile.get("motivations", [])) or "unknown"
        sources      = ", ".join(profile.get("sources_cited", []))
        generated    = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
        mitre_id     = profile.get("mitre_group_id", "")

        description = (
            f"Actor: {actor_name}"
            + (f" ({mitre_id})" if mitre_id else "")
            + (f" | Origin: {origin}" if origin else "")
            + f" | Motivation: {motivations}"
            + f" | Sources: {sources}"
            + f" | Generated by THEORY {generated}"
        )

        techniques_in   = profile.get("techniques", [])
        technique_entries = self._build_technique_entries(techniques_in)

        layer = {
            "name":        f"{actor_name} — THEORY",
            "versions": {
                "attack":    ATTACK_VERSION,
                "navigator": NAVIGATOR_VERSION,
                "layer":     LAYER_FORMAT,
            },
            "domain":      "enterprise-attack",
            "description": description,
            "filters": {
                "platforms": [
                    "Windows", "macOS", "Linux",
                    "Office 365", "Azure AD", "IaaS",
                    "Google Workspace", "Network", "Containers",
                ],
            },
            "sorting":     3,          # sort descending by score (HIGH first)
            "layout": {
                "layout":               "side",
                "showName":             True,
                "showID":               True,
                "showAggregateScores":  True,
                "countUnscored":        False,
                "aggregateFunction":    "max",
                "expandedSubtechniques": "annotated",
            },
            "hideDisabled": False,
            "techniques":   technique_entries,
            "gradient": {
                "colors":   ["#ffe680", "#ffaa00", "#ff6666"],
                "minValue": 0,
                "maxValue": 100,
            },
            "legendItems": [
                {"label": "HIGH confidence (2+ sources)",    "color": "#ff6666"},
                {"label": "MEDIUM confidence (1 auth source)", "color": "#ffaa00"},
                {"label": "LOW confidence (1 community source)", "color": "#ffe680"},
            ],
            "metadata": [
                {"name": "generated_by",  "value": "THEORY"},
                {"name": "actor",         "value": actor_name},
                {"name": "sources_cited", "value": sources},
                {"name": "generated_at",  "value": generated},
            ],
            "showTacticRowBackground": True,
            "tacticRowBackground":     "#1a1a2e",
            "selectTechniquesAcrossTactics": False,
            "selectSubtechniquesWithParent": False,
        }

        return layer

    def _build_technique_entries(
        self, techniques: list[dict]
    ) -> list[dict[str, Any]]:
        """
        Convert THEORY technique records to Navigator technique entries.

        Each unique technique_id gets one entry. If a technique appears
        under multiple tactics, we emit one entry per tactic so Navigator
        colors it correctly under each column.
        """
        entries: list[dict] = []
        seen: set[str] = set()

        for t in techniques:
            tid        = (t.get("technique_id") or "").strip().upper()
            if not tid:
                continue

            confidence = (t.get("confidence") or "LOW").upper()
            color      = CONFIDENCE_COLORS.get(confidence, CONFIDENCE_COLORS["LOW"])
            score      = CONFIDENCE_SCORES.get(confidence, 30)
            tactic_raw = (t.get("tactic") or "").strip()
            tactic_id  = TACTIC_SLUGS.get(tactic_raw, tactic_raw.lower().replace(" ", "-"))

            # Build comment — include Sigma coverage if present
            sigma_rules = t.get("sigma_rules", [])
            sigma_count = len(sigma_rules)
            name        = t.get("technique_name") or t.get("name", "")
            detection   = t.get("detection", "")

            comment_parts = [f"Confidence: {confidence}"]
            if sigma_count:
                top = sigma_rules[0].get("title", "")
                comment_parts.append(
                    f"Sigma: {sigma_count} rule{'s' if sigma_count != 1 else ''}"
                    + (f" — {top}" if top else "")
                )
            elif detection:
                comment_parts.append(f"Detection: {detection[:120]}")

            comment = " | ".join(comment_parts)

            # Deduplicate by tid+tactic combo
            key = f"{tid}::{tactic_id}"
            if key in seen:
                continue
            seen.add(key)

            entry: dict[str, Any] = {
                "techniqueID": tid,
                "color":       color,
                "score":       score,
                "comment":     comment,
                "enabled":     True,
            }

            # Only set tactic if we have a valid one
            if tactic_id:
                entry["tactic"] = tactic_id

            # Show subtechniques expanded if any sigma rules exist
            if sigma_count and "." not in tid:
                entry["showSubtechniques"] = True

            entries.append(entry)

        return entries

    def save(self, profile: dict[str, Any]) -> Path:
        """Write the Navigator layer to output/dossiers/<actor>.navigator.json"""
        OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
        slug = _slugify(profile.get("actor_name", "unknown"))

        # Use canonical slug if possible
        try:
            from collectors.cisa_advisories import ALIAS_TABLE
            actor_lower = profile.get("actor_name", "").lower()
            for canonical, aliases in ALIAS_TABLE.items():
                if canonical.lower() == actor_lower or actor_lower in aliases:
                    slug = _slugify(canonical)
                    break
        except Exception:
            pass

        path  = OUTPUT_DIR / f"{slug}.navigator.json"
        layer = self.build_layer(profile)
        path.write_text(
            json.dumps(layer, indent=2, ensure_ascii=False),
            encoding="utf-8",
        )
        logger.info("Navigator layer saved → %s", path)
        return path

    def to_string(self, profile: dict[str, Any]) -> str:
        """Return the layer JSON as a string (for --no-save)."""
        return json.dumps(self.build_layer(profile), indent=2, ensure_ascii=False)


# ---------------------------------------------------------------------------
# Utilities
# ---------------------------------------------------------------------------

def _slugify(name: str) -> str:
    return re.sub(r"[^a-z0-9]", "_", name.lower())
